"""initial schema

Revision ID: 74858962b483
Revises: 
Create Date: 2026-03-30 15:40:48.339863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74858962b483'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('Equipment_ID', sa.Integer(), nullable=False),
    sa.Column('Equipment_Name', sa.String(), nullable=True),
    sa.Column('Equipment_Category', sa.String(), nullable=True),
    sa.Column('Equipment_Location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('Equipment_ID')
    )
    op.create_index(op.f('ix_equipment_Equipment_ID'), 'equipment', ['Equipment_ID'], unique=False)
    op.create_index(op.f('ix_equipment_Equipment_Name'), 'equipment', ['Equipment_Name'], unique=False)
    op.create_table('products',
    sa.Column('Product_ID', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_kcal', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('product_protein', sa.Float(), nullable=True),
    sa.Column('product_carbs', sa.Float(), nullable=True),
    sa.Column('product_fat', sa.Float(), nullable=True),
    sa.Column('product_fiber', sa.Float(), nullable=True),
    sa.Column('product_sugar', sa.Float(), nullable=True),
    sa.Column('product_sodium', sa.Float(), nullable=True),
    sa.Column('product_chol', sa.Float(), nullable=True),
    sa.Column('Product_Diet_Tags', sa.String(), nullable=True),
    sa.Column('Product_Price_Category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Product_ID')
    )
    op.create_index(op.f('ix_products_Product_ID'), 'products', ['Product_ID'], unique=False)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_table('users',
    sa.Column('User_ID', sa.Integer(), nullable=False),
    sa.Column('User_mail', sa.String(), nullable=True),
    sa.Column('User_password', sa.String(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('User_Subscription', sa.String(), nullable=True),
    sa.Column('User_age', sa.Integer(), nullable=True),
    sa.Column('User_weight', sa.Float(), nullable=True),
    sa.Column('User_Height', sa.Float(), nullable=True),
    sa.Column('User_gender', sa.String(), nullable=True),
    sa.Column('User_Goals', sa.String(), nullable=True),
    sa.Column('User_Allergies', sa.String(), nullable=True),
    sa.Column('User_Dietary_Preferences', sa.String(), nullable=True),
    sa.Column('User_Budget_Level', sa.String(), nullable=True),
    sa.Column('User_Injuries', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('User_ID')
    )
    op.create_index(op.f('ix_users_User_ID'), 'users', ['User_ID'], unique=False)
    op.create_index(op.f('ix_users_User_mail'), 'users', ['User_mail'], unique=True)
    op.create_table('biometrics_logs',
    sa.Column('Log_ID', sa.Integer(), nullable=False),
    sa.Column('User_ID', sa.Integer(), nullable=True),
    sa.Column('Log_Date', sa.Date(), nullable=True),
    sa.Column('Weight', sa.Float(), nullable=True),
    sa.Column('Sleep_Hours', sa.Float(), nullable=True),
    sa.Column('Heart_Rate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['User_ID'], ['users.User_ID'], ),
    sa.PrimaryKeyConstraint('Log_ID')
    )
    op.create_index(op.f('ix_biometrics_logs_Log_ID'), 'biometrics_logs', ['Log_ID'], unique=False)
    op.create_table('meal_logs',
    sa.Column('Log_ID', sa.Integer(), nullable=False),
    sa.Column('User_ID', sa.Integer(), nullable=True),
    sa.Column('Product_ID', sa.Integer(), nullable=True),
    sa.Column('Log_Date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Product_ID'], ['products.Product_ID'], ),
    sa.ForeignKeyConstraint(['User_ID'], ['users.User_ID'], ),
    sa.PrimaryKeyConstraint('Log_ID')
    )
    op.create_index(op.f('ix_meal_logs_Log_ID'), 'meal_logs', ['Log_ID'], unique=False)
    op.create_table('user_equipment',
    sa.Column('User_ID', sa.Integer(), nullable=False),
    sa.Column('Equipment_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Equipment_ID'], ['equipment.Equipment_ID'], ),
    sa.ForeignKeyConstraint(['User_ID'], ['users.User_ID'], ),
    sa.PrimaryKeyConstraint('User_ID', 'Equipment_ID')
    )
    op.create_table('workout_sessions',
    sa.Column('Session_ID', sa.Integer(), nullable=False),
    sa.Column('User_ID', sa.Integer(), nullable=True),
    sa.Column('Session_Date', sa.Date(), nullable=True),
    sa.Column('Session_MaxBpm', sa.Integer(), nullable=True),
    sa.Column('Session_AvgBpm', sa.Integer(), nullable=True),
    sa.Column('Session_RestingBpm', sa.Integer(), nullable=True),
    sa.Column('Session_Duration', sa.Integer(), nullable=True),
    sa.Column('Session_Type', sa.String(), nullable=True),
    sa.Column('User_Feedback_Score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['User_ID'], ['users.User_ID'], ),
    sa.PrimaryKeyConstraint('Session_ID')
    )
    op.create_index(op.f('ix_workout_sessions_Session_ID'), 'workout_sessions', ['Session_ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sessions_Session_ID'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_table('user_equipment')
    op.drop_index(op.f('ix_meal_logs_Log_ID'), table_name='meal_logs')
    op.drop_table('meal_logs')
    op.drop_index(op.f('ix_biometrics_logs_Log_ID'), table_name='biometrics_logs')
    op.drop_table('biometrics_logs')
    op.drop_index(op.f('ix_users_User_mail'), table_name='users')
    op.drop_index(op.f('ix_users_User_ID'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_Product_ID'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_equipment_Equipment_Name'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_Equipment_ID'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
